// code-resource/nuxt-vue/Header.vue
<template>
  <div id="header" class="header flex flex-center">
    <div class="header__inner container flex align-center">

      <div class="flex-1"> <nuxt-link class="logo" to="/">Logo</nuxt-link></div>
      <div class="search-bar flex-1 d-block-sm"><form action=""><input type="text" /></form></div>
      <nav class="flex justify-end">
          <ul class="flex flex-center">
            <li>  <nuxt-link to="/flugger-test">FluggerTest</nuxt-link>  </li>
            <li>  <nuxt-link to="/test2">Test 2</nuxt-link>  </li>
            <li><nuxt-link to="/links">Links</nuxt-link></li>
            <li><nuxt-link to="/sb-tutorial">SBTutorial</nuxt-link></li>
            <li><nuxt-link to="/about">About</nuxt-link></li>
          </ul>
      </nav>
    </div>
  </div>
</template>

<script>
export default {};
</script>

<style lang="scss" scoped>
//Temporary colors
$border1: rgb(234, 234, 234);

#header {
  height: 55px;
  min-height: 85px;
  border-bottom: $border1 1px solid;
    
  &__inner {
    display: flex;
  }
  nav ul > li > a,
  .logo,
  .search-bar input {
    padding: 12px;
  }
  .search-bar {
    display: none;
    border:  $border1 1px solid;

    form {
      width: 100%;
    }
  }
  .search-bar,
  input {
    border-radius: 4px;
    width: 100%;
  }
  nav ul > li {
    
    cursor: pointer;
    > a {
      background: rgb(197, 245, 245);
    }
    &:not(:last-child) {
      margin-right: 5px;
    }
  }
}
</style>

// src/components/common/core-sections/Header.tsx
import s from "./header.module.scss";
import { IMenuItem } from '@/types/content';

type IProps = {
    menuItems: IMenuItem[];
};
export const Header = (pr: IProps) => {
  return (
    <div id="header" className={s["header flex flex-center"]}>
      <div
        className={[s["header__inner"], "container flex align-center"].join(
          " "
        )}
      >
        <div className={s["flex-1"]}>
          <a className={s["logo"]} href="/">
            Logo
          </a>
        </div>
        <div className={[s["search-bar"], "flex-1 d-block-sm"].join(" ")}>
          <form action="">
            <input type="text" />
          </form>
        </div>
        <nav className={"flex justify-end"}>
          <ul className={"flex flex-center"}>
            {pr.menuItems.map((item, index) => (
              <li key={`menuitem_${index}`}>
                <a
                  className={item.className}
                  href={item.href}
                >
                  {item.text}
                </a>
              </li>
            ))}
            {/* <li>
              <a href="/flugger-test">FluggerTest</a>
            </li>
            <li>
              <a href="/test2">Test 2</a>
            </li>
            <li>
              <a href="/links">Links</a>
            </li>
            <li>
              <a href="/sb-tutorial">SBTutorial</a>
            </li>
            <li>
              <a href="/about">About</a>
            </li> */}
          </ul>
        </nav>
      </div>
    </div>
  );
};
